require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/InverseOf:
  Enabled: false
